services:
  origin:
    build: src/origin/

  edge:
    build: src/edge/
    ports: 
      - "8080:80"
    environment:
      - ORIGIN_HOST=origin
      - EDGE_REGION=sfo3

  nameserver:
    build: src/nameserver/
    ports: 
      - "120:53/udp"

