[project]
name = "toy-cdn"
version = "0.1.0"
description = "Nameserver for toy CDN project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "geoip2>=5.2.0",
    "haversine>=2.9.0",
]
